---
openapi: 3.0.1
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: access_key
      in: query
info:
  title: API V1
  version: v1
paths:
  "/geolocation":
    post:
      summary: create geolocation
      parameters: []
      security:
      - api_key: []
      responses:
        '401':
          description: access denied
        '201':
          description: created
        '200':
          description: updated
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
              required:
              - address
  "/geolocation/{address}":
    parameters:
    - name: address
      in: path
      description: IP address or URL
      required: true
      schema:
        type: string
    get:
      summary: show geolocation
      security:
      - api_key: []
      responses:
        '401':
          description: access denied
        '200':
          description: successful
        '404':
          description: not found
    delete:
      summary: delete geolocation
      security:
      - api_key: []
      responses:
        '401':
          description: access denied
        '204':
          description: successful
        '404':
          description: not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
